#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace toptask3.sv --exe signextend.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtoptask3.mk Vtoptask3

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vtoptask3
echo "\nSimulation completed"